//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mon_pass
{
    using System;
    using System.Collections.Generic;
    
    public partial class more
    {
        public long id { get; set; }
        public Nullable<long> main_id { get; set; }
        public string pass_n { get; set; }
        public string prod_name { get; set; }
    }
}
